'use strict';

export enum RoleType {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  PRODUCER = 'ROLE_PRODUCER',
  TRANSPORT = 'ROLE_TRANSPORT',
  DISTRIBUTOR = 'ROLE_DISTRIBUTOR',
  OWNER = 'ROLE_OWNER'
}
